apiVersion: v1
kind: Service
metadata:
    name: stupid-server
    labels:
        app: stupid-server
spec:
    selector:
        app: stupid-server
    ports:
        - port: 8000
          protocol: TCP
          nodePort: 30063
    type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: stupid-server
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: stupid-server
        spec:
            containers:
                - name: stupid-server
                  image: node-web-app
                  ports:
                      - containerPort: 8000
                - name: postgres
                    image: postgres
                    ports:
                        - containerPort: 27017
                    env:
                        - name: POSTGRES_PASSWORD
                          value: "password"
                        - name: POSTGRES_DB
                          value: "matcha"
                        - name: POSTGRES_USER
                          value: "admin"
