apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-matcha
  template:
    metadata:
      labels:
        app: react-app-matcha
    spec:
      containers:
        - name: react-app-matcha
          image: react-app-matcha
          resources:
            requests:
              cpu: "1"
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: source-code
              mountPath: /usr/src/app
          env:
            - name: CHOKIDAR_USEPOLLING
              value: "true"
      volumes:
        - name: source-code
          hostPath:
            path: /Users/agiulian/dev/matcha/client
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  labels:
    app: react-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 30080
  selector:
    app: react-app-matcha
